=== wgh19950620/xmldemo/model/src/main/resources/config/orch.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="orch">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="province">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="areaCodes">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="areaCode" maxOccurs="unbounded">
                                            <xsd:complexType>
                                                <xsd:attribute name="value">
                                                    <xsd:simpleType>
                                                        <xsd:restriction base="xsd:string">
                                                            <xsd:minLength value="1"/>
                                                        </xsd:restriction>
                                                    </xsd:simpleType>
                                                </xsd:attribute>
                                                <xsd:attribute name="cityCode">
                                                    <xsd:simpleType>
                                                        <xsd:restriction base="xsd:string">
                                                            <xsd:minLength value="1"/>
                                                        </xsd:restriction>
                                                    </xsd:simpleType>
                                                </xsd:attribute>
                                                <xsd:attribute name="comment" type="xsd:string"/>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== wgh19950620/xmldemo/model/src/main/resources/config/orch.xml
<?xml version="1.0" encoding="UTF-8"?>
<orch xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="orch.xsd">
    <province>
        <areaCodes>
            <areaCode value="3" comment="南京"/>
            <areaCode value="20" comment="苏州"/>
            <areaCode value="15" comment="无锡"/>
            <areaCode value="69" comment="常州"/>
            <areaCode value="4" comment="镇江"/>
            <areaCode value="33" comment="扬州"/>
            <areaCode value="26" comment="南通"/>
            <areaCode value="79" comment="泰州"/>
            <areaCode value="48" comment="徐州"/>
            <areaCode value="60" comment="淮安"/>
            <areaCode value="39" comment="盐城"/>
            <areaCode value="63" comment="连云港"/>
            <areaCode value="84" comment="宿迁"/>
        </areaCodes>
    </province>
</orch>
